apiVersion: v1
kind: Service
metadata:
  name: hello-bot-service
  namespace: default
spec:
  selector:
    app: hello-bot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP   # или LoadBalancer, если нужен внешний доступ
